#!/usr/bin/env python3
"""Keep fake phones visible on the SOH dashboard without streaming audio.

This writes the same Firestore device docs and Redis live-state keys that the
admin/SOH page reads. It does not connect to the gateway and it does not add
audio frames to the Redis stream, so it avoids the inference path entirely.

Requires:
    pip install -r scripts/requirements.txt
    gcloud auth application-default login
    export GOOGLE_CLOUD_PROJECT=<your-project>

Memorystore has a private IP, so run this from a network that can reach Redis
(for example VPN/bastion into the VPC, or a small VM in the VPC).
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import sys
import time
import uuid
from dataclasses import asdict, dataclass


DEFAULT_BASE_LAT = 38.8977
DEFAULT_BASE_LON = -77.0365
DEFAULT_INTERVAL_SECONDS = 180
DEFAULT_REDIS_TTL_SECONDS = 300


@dataclass
class LiveDeviceState:
    device_id: str
    session_id: str
    last_seen_ms: int
    last_sequence: int
    frames_received: int
    dropped_frames: int
    reconnect_count: int
    app_version: str
    network_type: str
    battery_percent: int
    thermal_state: str
    site_label: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Simulate low-cost SOH activity for fake phones."
    )
    parser.add_argument("--project", default=os.environ.get("GOOGLE_CLOUD_PROJECT", ""))
    parser.add_argument("--firestore-database", default="(default)")
    parser.add_argument("--collection", default="devices")
    parser.add_argument("--redis-host", required=True)
    parser.add_argument("--redis-port", type=int, default=6379)
    parser.add_argument("--redis-db", type=int, default=0)
    parser.add_argument("--count", type=int, default=10)
    parser.add_argument("--prefix", default="FAKE-SOH-PHONE")
    parser.add_argument("--site", default="SOH Test")
    parser.add_argument("--interval-seconds", type=int, default=DEFAULT_INTERVAL_SECONDS)
    parser.add_argument("--redis-ttl-seconds", type=int, default=DEFAULT_REDIS_TTL_SECONDS)
    parser.add_argument("--base-lat", type=float, default=DEFAULT_BASE_LAT)
    parser.add_argument("--base-lon", type=float, default=DEFAULT_BASE_LON)
    parser.add_argument(
        "--once",
        action="store_true",
        help="Write one refresh and exit instead of looping.",
    )
    return parser.parse_args()


def now_ms() -> int:
    return int(time.time() * 1000)


def device_id(prefix: str, n: int) -> str:
    return f"{prefix}-{n:03d}"


def location(base_lat: float, base_lon: float, n: int) -> tuple[float, float]:
    # Small deterministic spread so the markers do not sit on top of each other.
    row = (n - 1) // 5
    col = (n - 1) % 5
    return base_lat + row * 0.004, base_lon + col * 0.004


def upsert_firestore_devices(
    db,
    geo_point,
    *,
    collection: str,
    count: int,
    prefix: str,
    site: str,
    base_lat: float,
    base_lon: float,
    timestamp_ms: int,
) -> None:
    batch = db.batch()
    for n in range(1, count + 1):
        did = device_id(prefix, n)
        lat, lon = location(base_lat, base_lon, n)
        doc = db.collection(collection).document(did)
        batch.set(
            doc,
            {
                "device_id": did,
                "state": "active",
                "assigned_site_label": site,
                "app_version": "sim-soh-1.0",
                "device_model": "SOH simulator",
                "os_version": "local-only",
                "first_seen_ms": timestamp_ms,
                "last_seen_ms": timestamp_ms,
                "last_handshake_ms": timestamp_ms,
                "current_location": geo_point(lat, lon),
                "location_accuracy_m": 5.0,
                "location_status": "current",
                "location_timestamp_ms": timestamp_ms,
                "admin_notes": "Generated by scripts/simulate_soh_phones.py",
            },
            merge=True,
        )
    batch.commit()


def refresh_redis(
    client,
    *,
    count: int,
    prefix: str,
    site: str,
    timestamp_ms: int,
    ttl_seconds: int,
    tick: int,
) -> None:
    pipe = client.pipeline(transaction=False)
    for n in range(1, count + 1):
        did = device_id(prefix, n)
        state = LiveDeviceState(
            device_id=did,
            session_id=f"sim-{uuid.uuid4().hex[:12]}",
            last_seen_ms=timestamp_ms,
            last_sequence=tick,
            frames_received=tick,
            dropped_frames=0,
            reconnect_count=max(0, tick - 1),
            app_version="sim-soh-1.0",
            network_type="wifi",
            battery_percent=max(35, 96 - n),
            thermal_state="nominal",
            site_label=site,
        )
        pipe.set(f"device:{did}", json.dumps(asdict(state)), ex=ttl_seconds)
    pipe.execute()


def main() -> int:
    args = parse_args()
    if not args.project:
        print(
            "Missing --project or GOOGLE_CLOUD_PROJECT.",
            file=sys.stderr,
        )
        return 2

    import redis
    from google.cloud import firestore

    db = firestore.Client(project=args.project, database=args.firestore_database)
    redis_client = redis.Redis(
        host=args.redis_host,
        port=args.redis_port,
        db=args.redis_db,
        decode_responses=True,
    )
    redis_client.ping()

    stop = False

    def _stop(_signum: int, _frame: object) -> None:
        nonlocal stop
        stop = True

    signal.signal(signal.SIGINT, _stop)
    signal.signal(signal.SIGTERM, _stop)

    tick = 0
    while not stop:
        tick += 1
        ts = now_ms()
        upsert_firestore_devices(
            db,
            collection=args.collection,
            geo_point=firestore.GeoPoint,
            count=args.count,
            prefix=args.prefix,
            site=args.site,
            base_lat=args.base_lat,
            base_lon=args.base_lon,
            timestamp_ms=ts,
        )
        refresh_redis(
            redis_client,
            count=args.count,
            prefix=args.prefix,
            site=args.site,
            timestamp_ms=ts,
            ttl_seconds=args.redis_ttl_seconds,
            tick=tick,
        )
        print(
            f"refreshed {args.count} fake phones at {ts}; "
            f"next refresh in {args.interval_seconds}s",
            flush=True,
        )
        if args.once:
            break
        for _ in range(args.interval_seconds):
            if stop:
                break
            time.sleep(1)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
